#!/bin/sh
# Copyright 2022-2024 The Ramble Authors
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

#
# Description:
#     Runs Spack unit tests.
#
# Usage:
#     run-unit-tests [test ...]
#
# Options:
#     Optionally add one or more unit tests
#     to only run these tests.
#

#-----------------------------------------------------------
# Run a few initial commands and set up test environment
#-----------------------------------------------------------
ORIGINAL_PATH="$PATH"
ERROR=0

. "$(dirname $0)/setup.sh"
check_dependencies $coverage git hg svn
if [ $? != 0 ]; then
    ERROR=1
fi

# Move to root directory of Spack
# Allows script to be run from anywhere
cd "$RAMBLE_ROOT"

# Run spack help to cover command import
bin/ramble -h
if [ $? != 0 ]; then
    ERROR=1
fi
bin/ramble help -a
if [ $? != 0 ]; then
    ERROR=1
fi

export UNIT_TEST_COVERAGE_ADDOPTS=""
if [[ "$UNIT_TEST_COVERAGE" == "true" ]]; then
  export UNIT_TEST_COVERAGE_ADDOPTS="--cov --cov-report= --cov-config=pyproject.toml"
fi

export SERIAL_PYTEST_ADDOPTS=$PYTEST_ADDOPTS
export PARALLEL_PYTEST_ADDOPTS=""
# Check if xdist is available
if python -m pytest -VV 2>&1 | grep xdist; then
  export PARALLEL_PYTEST_ADDOPTS="-n 5"
fi

#-----------------------------------------------------------
# Run unit tests with code coverage
#-----------------------------------------------------------

echo "PARALLEL OPTS: ${PARALLEL_PYTEST_ADDOPTS}"

$(which ramble) unit-test ${PARALLEL_PYTEST_ADDOPTS} -x --verbose ${UNIT_TEST_COVERAGE_ADDOPTS}
if [ $? != 0 ]; then
    ERROR=1
fi


if [ $ERROR == 1 ]; then
    exit 1
fi
